/**
 * Mock AI Provider — simulates real AI responses without consuming API credits.
 * Used for development, testing, and hackathon demos.
 * Supports configurable fake latency and failure simulation.
 */

import {
  AIProvider,
  ChatRequest,
  ChatResponse,
  HealthCheckResult,
  ModelInfo,
  TokenUsage,
  normalizeProviderError,
} from "@/lib/providers/base";

const MOCK_MODELS: ModelInfo[] = [
  {
    id: "mock-fast",
    displayName: "Mock Fast (Instant)",
    description: "Simulates a fast model with ~100ms latency",
    maxInputTokens: 32000,
    maxOutputTokens: 4096,
    supportsStreaming: true,
    supportsVision: false,
  },
  {
    id: "mock-standard",
    displayName: "Mock Standard (~800ms)",
    description: "Simulates a standard model with ~800ms latency",
    maxInputTokens: 128000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsVision: false,
  },
  {
    id: "mock-slow",
    displayName: "Mock Slow (~2s)",
    description: "Simulates a slow model with ~2000ms latency",
    maxInputTokens: 200000,
    maxOutputTokens: 16384,
    supportsStreaming: true,
    supportsVision: false,
  },
];

const MOCK_RESPONSES = [
  "This is a simulated AI response from the mock provider. In production, this would be a real AI-generated response from the selected provider.",
  "The mock provider is working correctly. Your application successfully sent a request and received a response. This demonstrates that your integration logic is functional.",
  "Mock response: Your API integration is working as expected. The request was received, authenticated, and processed through the AI Sandbox gateway.",
  "Simulated AI output: Everything looks good with your setup! The authentication, request format, and response handling are all working correctly.",
  "This response was generated by the AI Sandbox mock provider. It simulates real AI provider behavior including token counting, latency, and response structure.",
];

function getLatencyForModel(modelId: string): number {
  switch (modelId) {
    case "mock-fast": return 80 + Math.random() * 100;
    case "mock-standard": return 600 + Math.random() * 400;
    case "mock-slow": return 1800 + Math.random() * 600;
    default: return 300 + Math.random() * 300;
  }
}

function estimateTokens(text: string): number {
  // Rough approximation: ~4 chars per token
  return Math.ceil(text.length / 4);
}

function selectMockResponse(userMessage: string): string {
  // Give slightly contextual responses for common test phrases
  const lower = userMessage.toLowerCase();
  if (lower.includes("hello") || lower.includes("hi")) {
    return "Hello! This is a mock AI response from AI Sandbox. Your integration is working correctly!";
  }
  if (lower.includes("summarize") || lower.includes("summary")) {
    return "Mock summary: This is a simulated summary response. Your document summarization integration appears to be working. In production, a real AI model would analyze and condense your content here.";
  }
  if (lower.includes("code") || lower.includes("function") || lower.includes("program")) {
    return "```python\n# Mock code response\ndef example_function():\n    # This is a simulated code response\n    return 'Your code integration is working!'\n```\n\nYour code-related API integration is functioning correctly.";
  }
  if (lower.includes("explain") || lower.includes("what is") || lower.includes("how")) {
    return "Mock explanation: This is a simulated explanatory response from the AI Sandbox mock provider. Your question-answering integration is working correctly. In production, a real AI model would provide a detailed, accurate explanation.";
  }
  return MOCK_RESPONSES[Math.floor(Math.random() * MOCK_RESPONSES.length)];
}

export class MockProvider implements AIProvider {
  readonly name = "mock";
  readonly displayName = "Mock Provider (Demo)";

  async healthCheck(): Promise<HealthCheckResult> {
    return { healthy: true, latencyMs: 5 };
  }

  async listModels(): Promise<ModelInfo[]> {
    return MOCK_MODELS;
  }

  async chat(request: ChatRequest): Promise<ChatResponse> {
    const startedAt = Date.now();

    // Validate model
    const model = MOCK_MODELS.find((m) => m.id === request.model);
    if (!model) {
      throw normalizeProviderError(
        new Error(`Model not found: ${request.model}`),
        this.displayName
      );
    }

    // Simulate latency
    const latency = getLatencyForModel(request.model);
    await new Promise((resolve) => setTimeout(resolve, latency));

    // Build response
    const userMessage = request.messages.filter((m: { role: string; content: string }) => m.role === "user").pop()?.content ?? "";
    const responseText = selectMockResponse(userMessage);

    const inputText = request.messages.map((m: { role: string; content: string }) => m.content).join(" ");
    const inputTokens = estimateTokens(inputText);
    const outputTokens = estimateTokens(responseText);

    const usage: TokenUsage = {
      inputTokens,
      outputTokens,
      totalTokens: inputTokens + outputTokens,
    };

    return {
      id: `mock_${Date.now()}_${Math.random().toString(36).slice(2)}`,
      model: request.model,
      content: responseText,
      usage,
      finishReason: "stop",
      latencyMs: Date.now() - startedAt,
    };
  }

  estimateCost(_usage: TokenUsage, _modelId: string): number {
    return 0; // Mock provider is free
  }
}
